if(${EXECUTE_MOVE} STREQUAL "TRUE")
    string(REPLACE "," ";" SL_EX "${SL_EXT}")
    #files to be moves
    foreach(ext_one ${SL_EX})
        if(${ext_one} STREQUAL "OFF")
            set(FILE_TO_MOVE_WILD  ${FILENAME_NO_EXT})
        else()
            set(FILE_TO_MOVE_WILD  ${FILENAME_NO_EXT}.*${ext_one}*)
        endif()
        file(GLOB FILES_TO_MOVE ${FILE_TO_MOVE_WILD})
        file(COPY ${FILES_TO_MOVE} DESTINATION ${FILES_MOVE_DESTINATION})
        MESSAGE(STATUS "QK-- COPIED ${FILES_TO_MOVE} FROM ${FILENAME_NO_EXT} TO ${FILES_MOVE_DESTINATION}")
    endforeach()
endif()